import { LocalityViewport } from './locality-viewport.interface';
import { UserPhoto } from './user-photo.type';
import { SingleSearchLocation } from './single-search-location.type';
import { SubscriptionPlanEnrollment } from './subscription-plan-enrollment.interface';
import { CroppedImageData } from './cropped-image-data.interface';

/**
 * User interface definition based on the actual database structure
 */
export interface User {
  id: bigint;
  display_name: string;
  first_name: string;
  last_name: string;
  gender: string;
  smoking?: string | null;
  drinking?: string | null;
  wants_children?: string | null;
  education?: string | null;
  has_children?: string | null;
  date_of_birth: Date;
  last_active_at?: Date | null;
  suspended_at?: Date | null;
  email_verified_at?: Date | null;
  suspended_reason?: string | null;
  bio?: string | null;
  seeking_genders: string[];
  email: string;
  height?: number | null;
  marital_status?: string | null;
  main_photo_cropped_image_data?: CroppedImageData;
  photos?: UserPhoto[];
  public_photos?: UserPhoto[];
  num_of_photos: number;
  main_photo?: string | null;
  public_main_photo?: string;
  interests?: string[];
  country?: string | null;
  location_name?: string | null;
  location_viewport?: LocalityViewport;
  latitude?: number | null;
  longitude?: number | null;
  seeking_distance_origin?: string | null;
  body_type?: string | null;
  timezone?: string | null;
  timezone_offset?: number | null;
  seeking_min_height: number;
  seeking_max_height: number;
  seeking_min_age: number;
  seeking_max_age: number;
  seeking_num_of_photos: number;
  seeking_max_distance: number;
  ethnicities?: string[];
  languages?: string[];
  religions?: string[];
  ethnic_preferences?: string[];
  religious_preferences?: string[];
  education_preferences?: string[];
  body_type_preferences?: string[];
  drinking_preferences?: string[];
  smoking_preferences?: string[];
  has_children_preferences?: string[];
  wants_children_preferences?: string[];
  interest_preferences?: string[];
  language_preferences?: string[];
  marital_status_preferences?: string[];
  seeking_countries?: string[];
  single_search_location?: SingleSearchLocation;
  required_min_age?: number | null;
  required_max_age?: number | null;
  required_min_height?: number | null;
  required_max_height?: number | null;
  required_religions?: string[];
  required_ethnicities?: string[];
  required_body_types?: string[];
  required_education_levels?: string[];
  required_marital_statuses?: string[];
  required_want_children_statuses?: string[];
  required_has_children_statuses?: string[];
  required_languages?: string[];
  payment_profile_id?: string | null;
  customer_payment_profile_id?: string | null;
  password: string;
  is_subscription_active: boolean;
  age: number;
  subscription_plan_enrollments: SubscriptionPlanEnrollment[];
  refresh_token?: string | null;
  created_at?: Date | null;
  updated_at?: Date | null;
}

