export interface Country {
  code: string;
  name: string;
  example?: string;
  regionLabel?: string;
}

export const countries: Country[] = [
  { code: 'AF', name: 'Afghanistan', example: 'Kabul' },
  { code: 'AX', name: 'Aland Islands', example: 'Mariehamn' },
  { code: 'AL', name: 'Albania', example: 'Tirana' },
  { code: 'DZ', name: 'Algeria', example: 'Algiers' },
  { code: 'AS', name: 'American Samoa', example: 'Pago Pago' },
  { code: 'AD', name: 'Andorra', example: 'Andorra la Vella' },
  { code: 'AO', name: 'Angola', example: 'Luanda' },
  { code: 'AI', name: 'Anguilla', example: 'The Valley, Central District' },
  { code: 'AQ', name: 'Antarctica', example: 'McMurdo Station, Ross Island' },
  { code: 'AG', name: 'Antigua and Barbuda', example: 'Saint John\'s' },
  { code: 'AR', name: 'Argentina', example: 'Buenos Aires', regionLabel: 'Province' },
  { code: 'AM', name: 'Armenia', example: 'Yerevan' },
  { code: 'AW', name: 'Aruba', example: 'Oranjestad' },
  { code: 'AU', name: 'Australia', example: 'Sydney, New South Wales', regionLabel: 'State' },
  { code: 'AT', name: 'Austria', example: 'Vienna', regionLabel: 'State' },
  { code: 'AZ', name: 'Azerbaijan', example: 'Baku' },
  { code: 'BS', name: 'Bahamas', example: 'Nassau, New Providence', regionLabel: 'District' },
  { code: 'BH', name: 'Bahrain', example: 'Manama, Capital Governorate', regionLabel: 'Governorate' },
  { code: 'BD', name: 'Bangladesh', example: 'Dhaka', regionLabel: 'Division' },
  { code: 'BB', name: 'Barbados', example: 'Bridgetown, Saint Michael', regionLabel: 'Parish' },
  { code: 'BY', name: 'Belarus', example: 'Minsk' },
  { code: 'BE', name: 'Belgium', example: 'Brussels' },
  { code: 'BZ', name: 'Belize', example: 'Belize City' },
  { code: 'BJ', name: 'Benin', example: 'Cotonou, Littoral' },
  { code: 'BM', name: 'Bermuda', example: 'Hamilton, Pembroke Parish' },
  { code: 'BT', name: 'Bhutan', example: 'Thimphu' },
  { code: 'BO', name: 'Bolivia', example: 'La Paz' },
  { code: 'BQ', name: 'Bonaire', example: 'Kralendijk, Bonaire' },
  { code: 'BA', name: 'Bosnia', example: 'Sarajevo' },
  { code: 'BW', name: 'Botswana', example: 'Gaborone, South-East District' },
  { code: 'BR', name: 'Brazil', example: 'São Paulo', regionLabel: 'State' },
  { code: 'BN', name: 'Brunei', example: 'Bandar Seri Begawan, Brunei-Muara District', regionLabel: 'District' },
  { code: 'BG', name: 'Bulgaria', example: 'Sofia City' },
  { code: 'BF', name: 'Burkina Faso', example: 'Ouagadougou, Burkina Faso' },
  { code: 'BI', name: 'Burundi', example: 'Bujumbura City' },
  { code: 'CV', name: 'Cabo Verde', example: 'Praia, Santo Antão' },
  { code: 'KH', name: 'Cambodia', example: 'Phnom Penh' },
  { code: 'CM', name: 'Cameroon', example: 'Yaoundé' },
  { code: 'CA', name: 'Canada', example: 'Toronto, Ontario', regionLabel: 'Province' },
  { code: 'KY', name: 'Cayman Islands' },
  { code: 'TD', name: 'Chad', example: 'N\'Djamena, Chari-Baguirmi' },
  { code: 'CL', name: 'Chile', example: 'Santiago', regionLabel: 'Region' },
  { code: 'CN', name: 'China', example: 'Beijing', regionLabel: 'Province' },
  { code: 'CX', name: 'Christmas Island' },
  { code: 'CC', name: 'Cocos Islands' },
  { code: 'CO', name: 'Colombia', example: 'Bogotá', regionLabel: 'Department' },
  { code: 'KM', name: 'Comoros', example: 'Moroni, Grande Comore' },
  { code: 'CG', name: 'Congo', example: 'Brazzaville' },
  { code: 'CK', name: 'Cook Islands' },
  { code: 'CR', name: 'Costa Rica', example: 'San José' },
  { code: 'HR', name: 'Croatia', example: 'Zagreb' },
  { code: 'CU', name: 'Cuba', example: 'Havana' },
  { code: 'CY', name: 'Cyprus', example: 'Nicosia' },
  { code: 'CZ', name: 'Czechia', example: 'Prague' },
  { code: 'DK', name: 'Denmark', example: 'Copenhagen' },
  { code: 'DJ', name: 'Djibouti', example: 'Djibouti' },
  { code: 'DM', name: 'Dominica', example: 'Roseau' },
  { code: 'DO', name: 'Dominican Republic', example: 'Santo Domingo' },
  { code: 'EC', name: 'Ecuador', example: 'Quito, Pichincha', regionLabel: 'Province' },
  { code: 'EG', name: 'Egypt', example: 'Cairo' },
  { code: 'SV', name: 'El Salvador', example: 'San Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea', example: 'Malabo, Río Muni' },
  { code: 'ER', name: 'Eritrea', example: 'Asmara, Maekel' },
  { code: 'EE', name: 'Estonia', example: 'Tallinn, Harju County', regionLabel: 'County' },
  { code: 'SZ', name: 'Eswatini', example: 'Mbabane, Hhohho Region', regionLabel: 'Region' },
  { code: 'ET', name: 'Ethiopia', example: 'Addis Ababa' },
  { code: 'FK', name: 'Falkland Islands' },
  { code: 'FO', name: 'Faroe Islands' },
  { code: 'FJ', name: 'Fiji', example: 'Suva' },
  { code: 'FI', name: 'Finland', example: 'Helsinki, Uusimaa', regionLabel: 'Region' },
  { code: 'FR', name: 'France', example: 'Paris' },
  { code: 'GF', name: 'French Guiana' },
  { code: 'PF', name: 'French Polynesia', example: 'Papeete' },
  { code: 'GA', name: 'Gabon', example: 'Libreville, Estuaire', regionLabel: 'Province' },
  { code: 'GM', name: 'Gambia', example: 'Banjul' },
  { code: 'GE', name: 'Georgia', example: 'Tbilisi' },
  { code: 'DE', name: 'Germany', example: 'Berlin', regionLabel: 'State' },
  { code: 'GH', name: 'Ghana', example: 'Accra' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GR', name: 'Greece', example: 'Athens, Attica', regionLabel: 'Region' },
  { code: 'GL', name: 'Greenland' },
  { code: 'GD', name: 'Grenada', example: 'St. George\'s' },
  { code: 'GP', name: 'Guadeloupe' },
  { code: 'GU', name: 'Guam' },
  { code: 'GT', name: 'Guatemala', example: 'Guatemala City' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'GN', name: 'Guinea', example: 'Conakry' },
  { code: 'GW', name: 'Guinea-Bissau', example: 'Bissau' },
  { code: 'GY', name: 'Guyana', example: 'Georgetown' },
  { code: 'HT', name: 'Haiti', example: 'Port-au-Prince' },
  { code: 'HN', name: 'Honduras', example: 'Tegucigalpa' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungary', example: 'Budapest' },
  { code: 'IS', name: 'Iceland', example: 'Reykjavík' },
  { code: 'IN', name: 'India', example: 'New Delhi', regionLabel: 'State' },
  { code: 'ID', name: 'Indonesia', example: 'Jakarta', regionLabel: 'Province' },
  { code: 'IR', name: 'Iran', example: 'Tehran' },
  { code: 'IQ', name: 'Iraq', example: 'Baghdad' },
  { code: 'IE', name: 'Ireland', example: 'Dublin' },
  { code: 'IM', name: 'Isle of Man' },
  { code: 'IL', name: 'Israel', example: 'Jerusalem' },
  { code: 'IT', name: 'Italy', example: 'Rome, Lazio', regionLabel: 'Region' },
  { code: 'JM', name: 'Jamaica', example: 'Kingston' },
  { code: 'JP', name: 'Japan', example: 'Tokyo', regionLabel: 'Prefecture' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JO', name: 'Jordan', example: 'Amman' },
  { code: 'KZ', name: 'Kazakhstan', example: 'Nur-Sultan', regionLabel: 'Region' },
  { code: 'KE', name: 'Kenya', example: 'Nairobi' },
  { code: 'KI', name: 'Kiribati', example: 'Tarawa' },
  { code: 'KW', name: 'Kuwait', example: 'Kuwait City' },
  { code: 'KG', name: 'Kyrgyzstan', example: 'Bishkek' },
  { code: 'LA', name: 'Laos', example: 'Vientiane' },
  { code: 'LV', name: 'Latvia', example: 'Riga' },
  { code: 'LB', name: 'Lebanon', example: 'Beirut' },
  { code: 'LS', name: 'Lesotho', example: 'Maseru' },
  { code: 'LR', name: 'Liberia', example: 'Monrovia, Montserrado' },
  { code: 'LY', name: 'Libya', example: 'Tripoli' },
  { code: 'LI', name: 'Liechtenstein', example: 'Vaduz' },
  { code: 'LT', name: 'Lithuania', example: 'Vilnius' },
  { code: 'LU', name: 'Luxembourg', example: 'Luxembourg' },
  { code: 'MO', name: 'Macao' },
  { code: 'MG', name: 'Madagascar', example: 'Antananarivo' },
  { code: 'MW', name: 'Malawi', example: 'Lilongwe' },
  { code: 'MY', name: 'Malaysia', example: 'Kuala Lumpur', regionLabel: 'State' },
  { code: 'MV', name: 'Maldives', example: 'Male' },
  { code: 'ML', name: 'Mali', example: 'Bamako' },
  { code: 'MT', name: 'Malta', example: 'Valletta' },
  { code: 'MH', name: 'Marshall Islands', example: 'Majuro' },
  { code: 'MQ', name: 'Martinique' },
  { code: 'MR', name: 'Mauritania', example: 'Nouakchott' },
  { code: 'MU', name: 'Mauritius', example: 'Port Louis' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'MX', name: 'Mexico', example: 'Mexico City', regionLabel: 'State' },
  { code: 'FM', name: 'Micronesia', example: 'Palikir, Pohnpei', regionLabel: 'State' },
  { code: 'MD', name: 'Moldova', example: 'Chisinau' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia', example: 'Ulaanbaatar' },
  { code: 'ME', name: 'Montenegro', example: 'Podgorica' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'MA', name: 'Morocco', example: 'Rabat' },
  { code: 'MZ', name: 'Mozambique', example: 'Maputo' },
  { code: 'MM', name: 'Myanmar', example: 'Naypyidaw' },
  { code: 'NA', name: 'Namibia', example: 'Windhoek, Erongo', regionLabel: 'Region' },
  { code: 'NR', name: 'Nauru', example: 'Yaren' },
  { code: 'NP', name: 'Nepal', example: 'Kathmandu, Bagmati', regionLabel: 'Province' },
  { code: 'NL', name: 'Netherlands', example: 'Amsterdam, North Holland', regionLabel: 'Province' },
  { code: 'NC', name: 'New Caledonia' },
  { code: 'NZ', name: 'New Zealand', example: 'Wellington' },
  { code: 'NI', name: 'Nicaragua', example: 'Managua' },
  { code: 'NE', name: 'Niger', example: 'Niamey' },
  { code: 'NG', name: 'Nigeria', example: 'Abuja', regionLabel: 'State' },
  { code: 'NU', name: 'Niue' },
  { code: 'NF', name: 'Norfolk Island' },
  { code: 'MK', name: 'North Macedonia', example: 'Skopje' },
  { code: 'NO', name: 'Norway', example: 'Oslo' },
  { code: 'OM', name: 'Oman', example: 'Muscat' },
  { code: 'PK', name: 'Pakistan', example: 'Islamabad', regionLabel: 'Province' },
  { code: 'PW', name: 'Palau', example: 'Ngerulmud' },
  { code: 'PA', name: 'Panama', example: 'Panama City' },
  { code: 'PG', name: 'Papua New Guinea', example: 'Port Moresby, National Capital', regionLabel: 'Province' },
  { code: 'PY', name: 'Paraguay', example: 'Asunción' },
  { code: 'PE', name: 'Peru', example: 'Lima' },
  { code: 'PH', name: 'Philippines', example: 'Cagayan de Oro, Misamis Oriental', regionLabel: 'Province' },
  { code: 'PN', name: 'Pitcairn' },
  { code: 'PL', name: 'Poland', example: 'Warsaw, Masovian', regionLabel: 'Voivodeship' },
  { code: 'PT', name: 'Portugal', example: 'Lisbon' },
  { code: 'QA', name: 'Qatar', example: 'Doha' },
  { code: 'RO', name: 'Romania', example: 'Bucharest' },
  { code: 'RU', name: 'Russia', example: 'Moscow', regionLabel: 'Federal Subject' },
  { code: 'RW', name: 'Rwanda', example: 'Kigali' },
  { code: 'BL', name: 'Saint Barthélemy', example: 'Gustavia, Saint Barthélemy' },
  { code: 'SH', name: 'Saint Helena', example: 'Jamestown, Saint Helena' },
  { code: 'KN', name: 'Saint Kitts and Nevis', example: 'Basseterre, Saint Kitts' },
  { code: 'LC', name: 'Saint Lucia', example: 'Castries' },
  { code: 'MF', name: 'Saint Martin', example: 'Marigot, Saint Martin' },
  { code: 'VC', name: 'Saint Vincent', example: 'Kingstown, Saint George' },
  { code: 'WS', name: 'Samoa', example: 'Apia, Tuamasaga' },
  { code: 'SM', name: 'San Marino', example: 'San Marino' },
  { code: 'SA', name: 'Saudi Arabia', example: 'Riyadh' },
  { code: 'SN', name: 'Senegal', example: 'Dakar' },
  { code: 'RS', name: 'Serbia', example: 'Belgrade' },
  { code: 'SC', name: 'Seychelles', example: 'Victoria, Mahé' },
  { code: 'SL', name: 'Sierra Leone', example: 'Freetown' },
  { code: 'SG', name: 'Singapore', example: 'Singapore' },
  { code: 'SX', name: 'Sint Maarten' },
  { code: 'SK', name: 'Slovakia', example: 'Bratislava' },
  { code: 'SI', name: 'Slovenia', example: 'Ljubljana' },
  { code: 'SB', name: 'Solomon Islands', example: 'Honiara' },
  { code: 'SO', name: 'Somalia', example: 'Mogadishu' },
  { code: 'ZA', name: 'South Africa', example: 'Pretoria, Gauteng', regionLabel: 'Province' },
  { code: 'GS', name: 'South Georgia' },
  { code: 'KR', name: 'South Korea', example: 'Seoul', regionLabel: 'Region/Province' },
  { code: 'SS', name: 'South Sudan', example: 'Juba' },
  { code: 'ES', name: 'Spain', example: 'Madrid', regionLabel: 'Community' },
  { code: 'LK', name: 'Sri Lanka', example: 'Colombo' },
  { code: 'SD', name: 'Sudan', example: 'Khartoum' },
  { code: 'SR', name: 'Suriname', example: 'Paramaribo, Sipaliwini' },
  { code: 'SE', name: 'Sweden', example: 'Stockholm' },
  { code: 'CH', name: 'Switzerland', example: 'Bern', regionLabel: 'Canton' },
  { code: 'SY', name: 'Syria', example: 'Damascus' },
  { code: 'TW', name: 'Taiwan', example: 'Taipei' },
  { code: 'TJ', name: 'Tajikistan', example: 'Dushanbe' },
  { code: 'TZ', name: 'Tanzania', example: 'Dodoma' },
  { code: 'TH', name: 'Thailand', example: 'Bangkok', regionLabel: 'Province' },
  { code: 'TL', name: 'Timor-Leste', example: 'Dili' },
  { code: 'TG', name: 'Togo', example: 'Lomé, Plateau' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'TO', name: 'Tonga', example: 'Nuku\'alofa, Tongatapu' },
  { code: 'TT', name: 'Trinidad and Tobago', example: 'Port of Spain' },
  { code: 'TN', name: 'Tunisia', example: 'Tunis' },
  { code: 'TR', name: 'Turkey', example: 'Ankara', regionLabel: 'Province' },
  { code: 'TM', name: 'Turkmenistan', example: 'Ashgabat' },
  { code: 'TC', name: 'Turks and Caicos' },
  { code: 'TV', name: 'Tuvalu', example: 'Funafuti' },
  { code: 'UG', name: 'Uganda', example: 'Kampala' },
  { code: 'UA', name: 'Ukraine', example: 'Kyiv' },
  { code: 'AE', name: 'United Arab Emirates', example: 'Abu Dhabi' },
  { code: 'GB', name: 'United Kingdom', example: 'London, England', regionLabel: 'Region/County' },
  { code: 'US', name: 'United States', example: 'Chicago, Illinois', regionLabel: 'State' },
  { code: 'UY', name: 'Uruguay', example: 'Montevideo' },
  { code: 'UZ', name: 'Uzbekistan', example: 'Tashkent' },
  { code: 'VU', name: 'Vanuatu', example: 'Port Vila, Shefa', regionLabel: 'Province' },
  { code: 'VE', name: 'Venezuela', example: 'Caracas, Miranda', regionLabel: 'State' },
  { code: 'VN', name: 'Vietnam', example: 'Hanoi' },
  { code: 'YE', name: 'Yemen', example: 'Sana\'a' },
  { code: 'ZM', name: 'Zambia', example: 'Lusaka' },
  { code: 'ZW', name: 'Zimbabwe', example: 'Harare' },
];
